CREATE DATABASE DATE_DB;

USE DATE_DB;

CREATE TABLE date_tbl
(OrderID INT PRIMARY KEY NOT NULL,
YEAR INT,
MONTH INT,
DAY INT);

INSERT INTO date_tbl(OrderID, YEAR, MONTH, DAY)
VALUES('1', '2020', '2', '14');
INSERT INTO date_tbl(OrderID, YEAR, MONTH, DAY)
VALUES('2', '2020', '2', '14');
INSERT INTO date_tbl(OrderID, YEAR, MONTH, DAY)
VALUES('3', '2020', '2', '14');
INSERT INTO date_tbl(OrderID, YEAR, MONTH, DAY)
VALUES('4', '2020', '2', '15');

SELECT * FROM date_tbl;

SELECT GETDATE() AS result;

SELECT DATEADD(MONTH, 2, '2020/02/14');
SELECT DATEADD(QUARTER, 2, '2020/02/14');
SELECT DATEADD(MONTH, -2, '2020/02/14');

SELECT CONCAT(MONTH + ' ', DAY)
FROM date_tbl WHERE OrderID = 1;

SELECT ABS(-234.5);
SELECT ROUND(234.46,1); 
SELECT ROUND(234.46,2); 
SELECT CEILING(234.1); 
SELECT FLOOR(234.1); 

SELECT SUBSTRING('JED SAMSON',1,5);
SELECT LENGTH('JED SAMSON');
