CREATE DATABASE FINALS_DB;

USE FINALS_DB; 

CREATE TABLE STUDENT_TBL(
STUD_ID VARCHAR(30) PRIMARY KEY NOT NULL,
STUD_LNAME VARCHAR(30),
STUD_FNAME VARCHAR(30),
STUD_MNAME VARCHAR(30),
STUD_SECTION VARCHAR(30)
);

INSERT INTO STUDENT_TBL(STUD_ID, STUD_LNAME, STUD_FNAME, STUD_MNAME, STUD_SECTION)
VALUES('C19-1803', 'DELA CRUZ', 'ANNA CLARISSE', 'TORRES', '2A'); 
INSERT INTO STUDENT_TBL(STUD_ID, STUD_LNAME, STUD_FNAME, STUD_MNAME, STUD_SECTION)
VALUES('C19-1719', 'MAICO', 'LEIREA VELLE', 'DALIVA', '2A'); 
INSERT INTO STUDENT_TBL(STUD_ID, STUD_LNAME, STUD_FNAME, STUD_MNAME, STUD_SECTION)
VALUES('C19-1749', 'RAMBAYON', 'LUIS ANTONIO', 'BAGUIO', '2A'); 
INSERT INTO STUDENT_TBL(STUD_ID, STUD_LNAME, STUD_FNAME, STUD_MNAME, STUD_SECTION)
VALUES('C19-1658', 'CRISTOBAL', 'MARK ADRIAN', 'ORNIDO', '2A'); 
INSERT INTO STUDENT_TBL(STUD_ID, STUD_LNAME, STUD_FNAME, STUD_MNAME, STUD_SECTION)
VALUES('C19-0337', 'HILARIA', 'CORNELIO JR.', 'LUCAS', '2A'); 

ALTER TABLE STUDENT_TBL ADD STUD_AGE INT(10);

UPDATE STUDENT_TBL SET STUD_AGE=20 WHERE STUD_ID='C19-1803';
UPDATE STUDENT_TBL SET STUD_AGE=19 WHERE STUD_ID='C19-1719';
UPDATE STUDENT_TBL SET STUD_AGE=19 WHERE STUD_ID='C19-1749';
UPDATE STUDENT_TBL SET STUD_AGE=20 WHERE STUD_ID='C19-1658';
UPDATE STUDENT_TBL SET STUD_AGE=22 WHERE STUD_ID='C19-0337';

ALTER TABLE STUDENT_TBL ADD SUBJECT VARCHAR(30);

UPDATE STUDENT_TBL SET SUBJECT='INFORMATION MANAGEMENT' WHERE STUD_LNAME='DELA CRUZ';
UPDATE STUDENT_TBL SET SUBJECT='COMPUTER ORGANIZATION' WHERE STUD_LNAME='MAICO';
UPDATE STUDENT_TBL SET SUBJECT='CISCO II' WHERE STUD_LNAME='RAMBAYON';
UPDATE STUDENT_TBL SET SUBJECT='FILDIS' WHERE STUD_LNAME='CRISTOBAL';
UPDATE STUDENT_TBL SET SUBJECT='SPORTS' WHERE STUD_LNAME='HILARIA';

ALTER TABLE STUDENT_TBL ADD FINAL_GRADE INT(10);

UPDATE STUDENT_TBL SET FINAL_GRADE=85 WHERE STUD_LNAME='DELA CRUZ';
UPDATE STUDENT_TBL SET FINAL_GRADE=87 WHERE STUD_LNAME='MAICO';
UPDATE STUDENT_TBL SET FINAL_GRADE=86 WHERE STUD_LNAME='RAMBAYON';
UPDATE STUDENT_TBL SET FINAL_GRADE=88 WHERE STUD_LNAME='CRISTOBAL';
UPDATE STUDENT_TBL SET FINAL_GRADE=84 WHERE STUD_LNAME='HILARIA';

SELECT * FROM STUDENT_TBL
ORDER BY STUD_LNAME;

SELECT MIN(STUD_AGE) FROM STUDENT_TBL;
SELECT MAX(STUD_AGE) FROM STUDENT_TBL;

SELECT AVG(FINAL_GRADE) FROM STUDENT_TBL;

SELECT SUM(FINAL_GRADE) FROM STUDENT_TBL;

ALTER TABLE STUDENT_TBL DROP COLUMN STUD_MNAME;

TRUNCATE TABLE STUDENT_TBL;
