CREATE DATABASE FINAL_DB;

DROP DATABASE FINAL_DB;

USE FINAL_DB;

CREATE TABLE FIN_TBL
(FID INT(5) PRIMARY KEY NOT NULL,
FFNAME VARCHAR (30),
FFPROD VARCHAR (20),
FFQUANTITY INT(20),
FFPRICE INT(20));

DROP TABLE FIN_TBL;

INSERT INTO FIN_TBL(FID, FFNAME, FFPROD, FFQUANTITY, FFPRICE)
VALUES('0111', 'SABEL', 'SAFEGUARD', '12', '24');

INSERT INTO FIN_TBL(FID, FFNAME, FFPROD, FFQUANTITY, FFPRICE)
VALUES('0112', 'JED', 'PHCARE', '24', '55');

INSERT INTO FIN_TBL(FID, FFNAME, FFPROD, FFQUANTITY, FFPRICE)
VALUES('0113', 'JELO', 'KNICKNACK', '20', '10');

INSERT INTO FIN_TBL(FID, FFNAME, FFPROD, FFQUANTITY, FFPRICE)
VALUES('0114', 'NIKA', 'MOCHI', '20', '15');

SELECT AVG(FFQUANTITY) FROM FIN_TBL;
SELECT SUM(FFPRICE) FROM FIN_TBL;
SELECT COUNT(FFQUANTITY), COUNT(FFPRICE) FROM FIN_TBL;
