CREATE DATABASE AGGRE_DB;

DROP DATABASE AGGRE_DB;

USE AGGRE_DB;

CREATE TABLE MOVIE_TBL
(REFERENCE_NO INT(5) PRIMARY KEY NOT NULL,
MOVIE_NAME VARCHAR(50),
TRANSACTION_DATE VARCHAR(30),
SEAT_AVAILABLE INT(10),
MOVIE_ID INT(10));

DROP TABLE MOVIE_TBL;

INSERT INTO MOVIE_TBL(REFERENCE_NO,MOVIE_NAME,TRANSACTION_DATE,SEAT_AVAILABLE,MOVIE_ID)
VALUES('11', 'JUSTICE LEAGUE', '03-21-21', '4', '1');
INSERT INTO MOVIE_TBL(REFERENCE_NO,MOVIE_NAME,TRANSACTION_DATE,SEAT_AVAILABLE,MOVIE_ID)
VALUES('12', 'GODZILLA VS KONG', '03-30-21', '5', '2');
INSERT INTO MOVIE_TBL(REFERENCE_NO,MOVIE_NAME,TRANSACTION_DATE,SEAT_AVAILABLE,MOVIE_ID)
VALUES('13', 'FALCON AND THE WINTER SOLDIER', '03-31-21', '10', '5');
INSERT INTO MOVIE_TBL(REFERENCE_NO,MOVIE_NAME,TRANSACTION_DATE,SEAT_AVAILABLE,MOVIE_ID)
VALUES('14', 'WANDA AND VISION', '03-01-21', '4', '6');
INSERT INTO MOVIE_TBL(REFERENCE_NO,MOVIE_NAME,TRANSACTION_DATE,SEAT_AVAILABLE,MOVIE_ID)
VALUES('15', 'HARLEY QUINN', '03-23-21', '2', '1');

SELECT * FROM MOVIE_TBL;

TRUNCATE TABLE MOVIE_TBL;

ALTER TABLE MOVIE_TBL ADD DIRECTORS VARCHAR(30);

ALTER TABLE MOVIE_TBL DROP COLUMN DIRECTORS;

UPDATE MOVIE_TBL SET DIRECTORS='MR. ROSS' WHERE REFERENCE_NO=11;

UPDATE MOVIE_TBL SET DIRECTORS='MR. BANNER' WHERE MOVIE_NAME='GODZILLA VS KONG';

SELECT AVG(SEAT_AVAILABLE) FROM MOVIE_TBL;
SELECT SUM(SEAT_AVAILABLE) FROM MOVIE_TBL;
SELECT COUNT(MOVIE_ID) FROM MOVIE_TBL;
SELECT MIN(TRANSACTION_DATE) AS EARLIEST_DATE FROM MOVIE_TBL;
SELECT MAX(TRANSACTION_DATE) AS LATEST_DATE FROM MOVIE_TBL;
SELECT DISTINCT MOVIE_ID FROM MOVIE_TBL;

SELECT MAX(TRANSACTION_DATE), MIN(REFERENCE_NO) FROM MOVIE_TBL GROUP BY MOVIE_NAME;

