CREATE DATABASE MT2_DB;

USE MT2_DB;

CREATE TABLE MARKET_TBL
(MTID VARCHAR(10) PRIMARY KEY NOT NULL,
MTNAME VARCHAR(50),
MTADDRESS VARCHAR(50));

INSERT INTO MARKET_TBL(MTID, MTNAME, MTADDRESS)
VALUES('1','OISHI CARAMEL','YORK NEW CITY');

INSERT INTO MARKET_TBL(MTID, MTNAME, MTADDRESS)
VALUES('2', 'MY SANS','CITY Z');

INSERT INTO MARKET_TBL(MTID, MTNAME, MTADDRESS)
VALUES('3','NESTLE NIDO','SAN JUAN CITY');

SELECT MTADDRESS FROM MARKET_TBL WHERE MTID='2';
SELECT * FROM MARKET_TBL;
UPDATE MARKET_TBL SET MTNAME='NICO SANS' WHERE MTID='2';

USE MT2_DB;

CREATE TABLE SUPPLIER_TBL
(SID VARCHAR(10) NOT NULL,
SNAME VARCHAR(20),
SADDRESS VARCHAR(50),
SCONTACTNO INT(20));

INSERT INTO SUPPLIER_TBL(SID, SNAME, SADDRESS, SCONTACTNO)
VALUES('11-A-1', 'JUSTINE ARCAYNA', 'FILINVEST CITY', '4412212');

INSERT INTO SUPPLIER_TBL(SID, SNAME, SADDRESS, SCONTACTNO)
VALUES('11-B-1', 'JUSTIN SY', 'FILINVEST CITY', '4412212');

INSERT INTO SUPPLIER_TBL(SID, SNAME, SADDRESS, SCONTACTNO)
VALUES('12-C-4', 'JANINA HONG', 'CHINA TOWN CITY', '4332125');

SELECT * FROM SUPPLIER_TBL WHERE SCONTACTNO='4412212';
UPDATE SUPPLIER_TBL SET SCONTACTNO='3311226' WHERE SNAME='JUSTIN SY';
SELECT * FROM SUPPLIER_TBL;

