CREATE DATABASE MT2_DB;

USE MT2_DB;

CREATE TABLE MARKET_TBL
(MTID VARCHAR(10) PRIMARY KEY NOT NULL,
MTNAME VARCHAR(50),
MTADDRESS VARCHAR(50));

INSERT INTO MARKET_TBL(MTID, MTNAME, MTADDRESS)
VALUES('M001','SM TUNGKO','TUNGKO, SJDM');

INSERT INTO MARKET_TBL(MTID, MTNAME, MTADDRESS)
VALUES('M002', 'FAIRVIEW TERRACES','NOVALICHES QC');

INSERT INTO MARKET_TBL(MTID, MTNAME, MTADDRESS)
VALUES('M003','ROBINSON EASY MARKET','NOVALICHES QC');

INSERT INTO MARKET_TBL(MTID, MTNAME, MTADDRESS)
VALUES('M004','PUREGOLD JR.','COMMONWEALTH, FAIRVIEW QC');

USE MT2_DB;

CREATE TABLE SUPPLIER_TBL
(SID VARCHAR(10) NOT NULL,
SNAME VARCHAR(20) PRIMARY KEY,
SADDRESS VARCHAR(50),
SCONTACTNO INT(20));

INSERT INTO SUPPLIER_TBL(SID, SNAME, SADDRESS, SCONTACTNO)
VALUES('S001', 'SUP1 CO.', 'FAIRVIEW, QUEZON CITY', '09999999');

INSERT INTO SUPPLIER_TBL(SID, SNAME, SADDRESS, SCONTACTNO)
VALUES('S002', 'STYLELEX CO.', 'CAVITE, CAVITE', '09111111');

INSERT INTO SUPPLIER_TBL(SID, SNAME, SADDRESS, SCONTACTNO)
VALUES('S003', 'BANGBANG CO.', 'BANABA, MARIKINA', '09887766');

INSERT INTO SUPPLIER_TBL(SID, SNAME, SADDRESS, SCONTACTNO)
VALUES('S004', 'PAWER CO.', 'FAIRVIEW, QUEZON CITY', '09334425');

USE MT2_DB;

CREATE TABLE PRODUCT_TBL
(PID VARCHAR(10) PRIMARY KEY NOT NULL,
PNAME VARCHAR(50),
PBRAND VARCHAR(50));

INSERT INTO PRODUCT_TBL(PID, PNAME, PBRAND)
VALUES('P001', 'REBISCO CRACKERS', 'LOCAL');

INSERT INTO PRODUCT_TBL(PID, PNAME, PBRAND)
VALUES('P002', 'RC COLA', 'LOCAL');

INSERT INTO PRODUCT_TBL(PID, PNAME, PBRAND)
VALUES('P003', 'SAFEGUARD', 'ABROAD');

INSERT INTO PRODUCT_TBL(PID, PNAME, PBRAND)
VALUES('P004', 'J AND J COTTON BUDS', 'ABROAD');

SELECT * FROM MARKET_TBL;
SELECT * FROM MARKET_TBL WHERE MTADDRESS='NOVALICHES QC';
SELECT * FROM SUPPLIER_TBL;
SELECT * FROM SUPPLIER_TBL WHERE SADDRESS='FAIRVIEW, QUEZON CITY';
SELECT * FROM PRODUCT_TBL WHERE PBRAND ='ABROAD';
SELECT * FROM PRODUCT_TBL WHERE PBRAND ='LOCAL';

